config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      post "new_comment", to: "comments#create", on: :member
      post "like_post", to: "likes#create", on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index], defaults: {format: :json} do
        resources :comments, only: [:index, :create]
      end
    end
  end

  resources :comments, only: [:destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    return unless user.present?

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, [Post, Comment, Like]
      can :update, [Post, Comment, Like], user_id: user.id
      can :destroy, [Post, Comment], user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  after_save :update_comment_counter

  def update_comment_counter
    post.comments_counter += 1
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.likes_counters += 1
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments, dependent: :destroy

  after_save :update_user_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counters, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def return_most_recent_comments
    comments.last(5)
  end

  private

  def update_user_post_counter
    user.posts_counter += 1
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist
  has_many :posts
  has_many :likes
  has_many :comments

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def return_last_three_posts
    posts.last(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      load_and_authorize_resource

      def index
        @comments = Comment.where({ post_id: params[:post_id] }).order('created_at DESC')
        render json: { success: true, data: { comments: @comments } }
      end

      def create
        comment = Comment.new(comments_params)
        comment.post_id = params[:post_id]
        comment.user = current_user

        if comment.save
          render json: { status: 201, message: 'Comment created successfully!', content: { comment: comment } }
        else
          render json: comment.errors, status: :bad_request, message: 'Operation failed'
        end
      end

      private

      def find_user
        User.find(params[:user_id])
      end

      def show_post
        find_user.posts.find(params[:post_id])
      end

      def comments_params
        params.require(:comment).permit(:text, :user_id, :post_id)
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        @posts = Post.all.order('created_at DESC')
        render json: { success: true, data: { comments: @posts } }
      end

      def show
        @show_post = current_user.posts.includes(:comments)
        render json: { success: true, data: { comments: @show_post } }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @post = Post.find(params[:id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = 'Your comment has been added!'
      redirect_to [@post.user, @post]
    else
      flash.now[:error] = 'Comment could not be added'
      render user_post_path
    end
  end

  def destroy
    puts 'Removing Comment'
    comment = Comment.find(params[:id])
    post = comment.post
    comment.destroy!
    flash[:success] = 'Removed comment!'
    redirect_back fallback_location: [post.user, post]
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylist'
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  load_and_authorize_resource

  def create
    post = Post.find(params[:id])
    like = current_user.likes.create(post: post)
    like.save!

    if like.save
      flash[:success] = 'Post Liked!'
      redirect_to user_post_path
    else
      flash.now[:error] = 'Like not added...'
      render user_post_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = User.find(params[:user_id]).posts.includes(:comments).find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
    render :new, locals: { post: @post }
  end

  def create
    @user = User.find(params[:user_id])
    add_post = @user.posts.new(post_params)
    add_post.comments_counter = 0
    add_post.likes_counters = 0
    respond_to do |format|
      format.html do
        if add_post.save
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_url
        else
          flash.now[:error] = 'Error: Post could not be created'
          render :new, locals: { post: add_post }
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    authorize! :destroy, post
    post.destroy!
    flash[:alert] = 'Deleted post'
    redirect_to user_posts_url
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SolarBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/29d7bf5b00.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "partials/navbar" %>  
    
    <% if notice.present? %>
      <div class="notification is-link is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/partials/_bio.html.erb
<div class="card mt-3">
  <div class="card-body">
    <h4 class="card-title">Bio</h4>
    <p class="card-text">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Fusce risus mi, luctus id ligula nec, malesuada rhoncus tortor.
      Ut egestas mollis erat. Aliquam imperdiet nisi ac porttitor imperdiet.
      Etiam lacus lorem, euismod eu porttitor porttitor, accumsan eget risus.
      Etiam at diam id nunc aliquet interdum ut in sapien. Sed ultrices
      eleifend massa, eget mattis magna sollicitudin fringilla.
      Mauris ac venenatis nisi, ac semper eros. Vivamus in facilisis ipsum.
    </p>
  </div>
</div>

app/views/partials/_comments.html.erb
<div class="card">
  <ul class="card-body">
    <h6>Comments</h6>
    <br/>
    <% comments.each do |comment| %>
    <li class="comment-box">
      <span><strong><%= comment.user.name %></strong>: <%= comment.text %></span>
      <% can?(:destroy, comment) %>
        <% if can? :destroy, comment %>
          <%= button_to 'Delete', comment_path(comment.id), method: :delete, class: "btn btn-danger"%>
        <% end %>
      <% end %>
    </li>
    <br/>
  </ul>
</div>

app/views/partials/_likes.html.erb
<%= form_with model:[@post, @post.likes.build], url: like_post_user_post_path, method: :post, local: true do |form| %>
  <%= form.submit "Add like", class: "btn btn-primary" %>
<% end %>
        

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <h3>SolarBlog</h3>
  <% if user_signed_in? %>
    <%= link_to "Home", root_path, class: "justify-content-center align-self-center" %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "justify-content-center align-self-center btn btn-primary" %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path, class: "justify-content-center align-self-center" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "justify-content-center align-self-center" %>
  <% end %>
</nav>

app/views/partials/_post_details.html.erb
<div class="card mt-3">
  <div class="card-body">
    <div class="header">
      <h3 class="card-title"><%= post.user.name %></h3>
    </div>
    <hr/>
    <div class="header">
      <h5>
        <%= post.title %>
      </h5>
      <p class="card-text"><small class="text-muted">Comments: <%= post.comments.size %>, Likes: <%= post.likes.size %></small></p>
    </div>
    <p class="card-text">
      <%= post.text %>
    </p>
    <div class="card-text d-flex justify-content-end">
      <%= render partial: "partials/likes" %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="card mt-3">
  <div class="card-body">
    <%= link_to user_post_path(@user.id, post.id), id: "user_post#{post.id}" do %> 
      <h4 class="card-title"><%= post.title %></h4>
      <p class="card-text">
        <%= post.text %>
      </p>
      <p class="card-text d-flex justify-content-end"><small class="text-muted">Comments: <%= post.comments.size %>, Likes: <%= post.likes.size %></small></p>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="user-posts">
  <%= render @user %>
  <div class="a-btn">
    <button class="btn btn-primary mt-3">
      <%= link_to 'Add New Post', new_user_post_path(@user.id) %>
    </button>
  </div>
  <% @posts.each do |post| %>
    <%= render post %>
    <%= render partial: "partials/comments", locals: {comments: post.comments } %>
    <% if can? :destroy, post %><%= button_to 'Delete Post', user_post_path(@user, post), method: :delete, class: 'delete btn btn-primary text-end' %><% end %>
  <% end %>

  <div class="a-btn">
    <button type="button" class="btn btn-primary mt-3">Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<div class="post-form">
  <div class="card new-post">
    <div class="card-body">
      <h1>Create a new post...</h1>
        <%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post, class: "form" do |form| %>
            <div class="mb-3">
              <%= form.label :post_title %>
              <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :your_post %>
              <%= form.text_area :text, class: "form-control text" %>
            </div>
            <div class="mb-3">
              <%= form.submit class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-details">
  <%= render partial: "partials/post_details", locals: {post: @post} %>
  <%= render partial: "partials/comments", locals: {comments: @post.comments } %>

  <hr/>

  <h1>Leave your comment here...</h1>
  <%= form_with url: new_comment_user_post_path do |form| %>
    <div class="mb-3">
      <%= form.text_area :text, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="card mt-3">
<%= link_to user do %>
  <div class="row g-0">
    <div class="col-md-2">
      <img src="<%= user.photo %>" width="100">
    </div>
    <div class="col-md-10">
      <div class="card-body">
        <h2 class="card-title"><%= user.name %></h2>
        <p class="card-text d-flex justify-content-end"><small class="text-muted">Number of posts: <%= user[:posts_counter] %></small></p>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/users/index.html.erb
<div class="home">
  <%= render @users %>
</div>

app/views/users/show.html.erb
<div class="user-details">
  <%= render @user %>
  <%= render partial: "partials/bio"%>
  <ul>
    <% @user.return_last_three_posts.each do |post|%>
      <%= render partial: "posts/post", locals: {post: post} %>
    <% end %>
  </ul>
  <div class="a-btn">
    <%=link_to "See all posts", user_posts_path(@user.id), class:"see-all btn btn-primary justify-content-center align-self-center", type: 'submit' , id: "see_all_#{@user.id}"%>
  </div>
</div>